---
Name: siteroutes
After:
  - "#rootroutes"
  - "#coreroutes"
---
SilverStripe\Control\Director:
  rules:
    "_styleguide": "Toast\\Controllers\\StyleGuideController"
    'api//$Action/$ID/$Name': 'Toast\Controllers\ApiController'