name: mercury
type: silverstripe
docroot: public
php_version: "8.2"
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.0"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
nodejs_version: "20"
web_extra_exposed_ports:
    - name: Vite Dev Server
      container_port: 5173
      http_port: 5173
      https_port: 5174
hooks:
 post-start:
   - exec: "yarn && yarn dev"